import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

def set_parameter_by_name(element, parameterName, value):
    element.LookupParameter(parameterName).Set(value)

import System.Drawing
import System.Windows.Forms
from System.Drawing import *
from System.Windows.Forms import *

class Form1(Form):
	def __init__(self):
		self.InitializeComponent()
	
	def InitializeComponent(self):
		self._button1 = System.Windows.Forms.Button()
		self._textBox1 = System.Windows.Forms.TextBox()
		self._label1 = System.Windows.Forms.Label()
		self._label2 = System.Windows.Forms.Label()
		self._button2 = System.Windows.Forms.Button()
		self.SuspendLayout()
		# 
		# button1
		# 
		self._button1.Location = System.Drawing.Point(197, 154)
		self._button1.Name = "button1"
		self._button1.Size = System.Drawing.Size(75, 23)
		self._button1.TabIndex = 0
		self._button1.Text = "Set"
		self._button1.UseVisualStyleBackColor = True
		self._button1.Click += self.Button1Click
		# 
		# textBox1
		# 
		self._textBox1.Location = System.Drawing.Point(127, 77)
		self._textBox1.Name = "textBox1"
		self._textBox1.Size = System.Drawing.Size(145, 20)
		self._textBox1.TabIndex = 1
		self._textBox1.TextChanged += self.TextBox1TextChanged
		# 
		# label1
		# 
		self._label1.Location = System.Drawing.Point(12, 80)
		self._label1.Name = "label1"
		self._label1.Size = System.Drawing.Size(100, 23)
		self._label1.TabIndex = 2
		self._label1.Text = "Set \"Comments\" :"
		# 
		# label2
		# 
		self._label2.Location = System.Drawing.Point(12, 41)
		self._label2.Name = "label2"
		self._label2.Size = System.Drawing.Size(100, 23)
		self._label2.TabIndex = 3
		self._label2.Text = "Select Element:"
		# 
		# button2
		# 
		self._button2.Location = System.Drawing.Point(127, 36)
		self._button2.Name = "button2"
		self._button2.Size = System.Drawing.Size(75, 23)
		self._button2.TabIndex = 4
		self._button2.Text = "Select"
		self._button2.UseVisualStyleBackColor = True
		self._button2.Click += self.Button2Click
		# 
		# Form1
		# 
		self.ClientSize = System.Drawing.Size(284, 207)
		self.Controls.Add(self._button2)
		self.Controls.Add(self._label2)
		self.Controls.Add(self._label1)
		self.Controls.Add(self._textBox1)
		self.Controls.Add(self._button1)
		self.Name = "Form1"
		self.Text = "SetParameter UI"
		self.ResumeLayout(False)
		self.PerformLayout()


	def TextBox1TextChanged(self, sender, e):
		pass

	def Button2Click(self, sender, e):
		sel = uidoc.Selection.PickObject(Selection.ObjectType.Element, 'Choose element')
		el = doc.GetElement(sel)
		self.select = el
		pass

	def Button1Click(self, sender, e):
		self.text = self._textBox1.Text
		TransactionManager.Instance.EnsureInTransaction(doc)
		for s in [self.select]:
			set_parameter_by_name(s,"Comments", self.text)
		TransactionManager.Instance.TransactionTaskDone()
		self.Close()

form = Form1()
Application.Run(form)
